### ISSUE TITLE
Add social menu

### ISSUE THREAD

**Issue by jstockdi** [Cloud-RI/cloud-ri.github.io#11]
Could this be a greenwood component?  ie, something other projects could use?

Could I somehow use https://github.com/ProjectEvergreen/greenwood/blob/master/www/components/social-icons/social-icons.js

And add meetup/linkedin, remove slack/twitter?

**Comment by thescientist13** [comment]
Yeah, feel free to grab it and add it!

**Comment by jstockdi** [comment]
Rocked out w/ just a few links in the header
