### ISSUE TITLE
Lighthouse SEO recommendations

### ISSUE THREAD

**Issue by thescientist13** [Cloud-RI/cloud-ri.github.io#5]
Did a quick Lighthouse report and found some low hanging fruit we could probably easily do and could probably be a _good first issue_ here for this repo.
![Screenshot 2023-11-05 at 1 38 30 PM](https://github.com/Cloud-RI/cloud-ri.github.io/assets/895923/ab0c9c29-8d6c-4521-8a00-781dd0af4e51)

Fixing the image would also help with Lighthouse a11y score as well.

---

Also, related to images and performance, it would be good to add height / width too.
![Screenshot 2023-11-05 at 1 45 16 PM](https://github.com/Cloud-RI/cloud-ri.github.io/assets/895923/7c7c629a-85b6-4bfd-905f-d2fff7d83768)

**Comment by jstockdi** [comment]
100% Lighthouse 🤷
